/***************************************************************************************************

  Zyan Disassembler Library (Zydis)

  Original Author : Florian Bernd

 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.

***************************************************************************************************/

/**
 * @file
 * CPUID feature flags taken from the ISA set Zydis already stores.
 *
 * A 128-bit or 256-bit AVX-512 set also reports `AVX512VL`. Sets whose
 * Zydis name ends in `128N` do not, because that suffix is the form that
 * does not require VL. No leaf, subleaf, register, or bit number is returned.
 */

#ifndef ZYDIS_CPUID_FLAGS_H
#define ZYDIS_CPUID_FLAGS_H

#include <Zycore/Defines.h>
#include <Zycore/Types.h>
#include <Zydis/DecoderTypes.h>
#include <Zydis/Status.h>

#ifdef __cplusplus
extern "C" {
#endif

#define ZYDIS_CPUID_FLAG_MAX_COUNT 2

typedef enum ZydisCpuidFlag_
{
    ZYDIS_CPUID_FLAG_NONE = 0,
    ZYDIS_CPUID_FLAG_ADOX_ADCX,
    ZYDIS_CPUID_FLAG_ADX,
    ZYDIS_CPUID_FLAG_AES,
    ZYDIS_CPUID_FLAG_AMD,
    ZYDIS_CPUID_FLAG_AMD3DNOW,
    ZYDIS_CPUID_FLAG_AMD_INVLPGB,
    ZYDIS_CPUID_FLAG_AMX,
    ZYDIS_CPUID_FLAG_AMX_BF16,
    ZYDIS_CPUID_FLAG_AMX_FP16,
    ZYDIS_CPUID_FLAG_AMX_INT8,
    ZYDIS_CPUID_FLAG_AMX_TILE,
    ZYDIS_CPUID_FLAG_APX_F,
    ZYDIS_CPUID_FLAG_AVX,
    ZYDIS_CPUID_FLAG_AVX2,
    ZYDIS_CPUID_FLAG_AVX2GATHER,
    ZYDIS_CPUID_FLAG_AVX512BW,
    ZYDIS_CPUID_FLAG_AVX512CD,
    ZYDIS_CPUID_FLAG_AVX512DQ,
    ZYDIS_CPUID_FLAG_AVX512ER,
    ZYDIS_CPUID_FLAG_AVX512F,
    ZYDIS_CPUID_FLAG_AVX512PF,
    ZYDIS_CPUID_FLAG_AVX512VL,
    ZYDIS_CPUID_FLAG_AVX512_4FMAPS,
    ZYDIS_CPUID_FLAG_AVX512_4VNNIW,
    ZYDIS_CPUID_FLAG_AVX512_BF16,
    ZYDIS_CPUID_FLAG_AVX512_BITALG,
    ZYDIS_CPUID_FLAG_AVX512_FP16,
    ZYDIS_CPUID_FLAG_AVX512_GFNI,
    ZYDIS_CPUID_FLAG_AVX512_IFMA,
    ZYDIS_CPUID_FLAG_AVX512_VAES,
    ZYDIS_CPUID_FLAG_AVX512_VBMI,
    ZYDIS_CPUID_FLAG_AVX512_VBMI2,
    ZYDIS_CPUID_FLAG_AVX512_VNNI,
    ZYDIS_CPUID_FLAG_AVX512_VP2INTERSECT,
    ZYDIS_CPUID_FLAG_AVX512_VPCLMULQDQ,
    ZYDIS_CPUID_FLAG_AVX512_VPOPCNTDQ,
    ZYDIS_CPUID_FLAG_AVXAES,
    ZYDIS_CPUID_FLAG_AVX_GFNI,
    ZYDIS_CPUID_FLAG_AVX_IFMA,
    ZYDIS_CPUID_FLAG_AVX_NE_CONVERT,
    ZYDIS_CPUID_FLAG_AVX_VNNI,
    ZYDIS_CPUID_FLAG_AVX_VNNI_INT16,
    ZYDIS_CPUID_FLAG_AVX_VNNI_INT8,
    ZYDIS_CPUID_FLAG_BMI1,
    ZYDIS_CPUID_FLAG_BMI2,
    ZYDIS_CPUID_FLAG_CET,
    ZYDIS_CPUID_FLAG_CLDEMOTE,
    ZYDIS_CPUID_FLAG_CLFLUSHOPT,
    ZYDIS_CPUID_FLAG_CLFSH,
    ZYDIS_CPUID_FLAG_CLWB,
    ZYDIS_CPUID_FLAG_CLZERO,
    ZYDIS_CPUID_FLAG_CMOV,
    ZYDIS_CPUID_FLAG_CMPCCXADD,
    ZYDIS_CPUID_FLAG_CMPXCHG16B,
    ZYDIS_CPUID_FLAG_ENQCMD,
    ZYDIS_CPUID_FLAG_F16C,
    ZYDIS_CPUID_FLAG_FAT_NOP,
    ZYDIS_CPUID_FLAG_FCMOV,
    ZYDIS_CPUID_FLAG_FCOMI,
    ZYDIS_CPUID_FLAG_FMA,
    ZYDIS_CPUID_FLAG_FMA4,
    ZYDIS_CPUID_FLAG_FRED,
    ZYDIS_CPUID_FLAG_FXSAVE,
    ZYDIS_CPUID_FLAG_FXSAVE64,
    ZYDIS_CPUID_FLAG_GFNI,
    ZYDIS_CPUID_FLAG_HRESET,
    ZYDIS_CPUID_FLAG_I186,
    ZYDIS_CPUID_FLAG_I286PROTECTED,
    ZYDIS_CPUID_FLAG_I286REAL,
    ZYDIS_CPUID_FLAG_I386,
    ZYDIS_CPUID_FLAG_I486,
    ZYDIS_CPUID_FLAG_I486REAL,
    ZYDIS_CPUID_FLAG_I86,
    ZYDIS_CPUID_FLAG_ICACHE_PREFETCH,
    ZYDIS_CPUID_FLAG_INVPCID,
    ZYDIS_CPUID_FLAG_KEYLOCKER,
    ZYDIS_CPUID_FLAG_KEYLOCKER_WIDE,
    ZYDIS_CPUID_FLAG_KNCE,
    ZYDIS_CPUID_FLAG_KNCJKBR,
    ZYDIS_CPUID_FLAG_KNCSTREAM,
    ZYDIS_CPUID_FLAG_KNCV,
    ZYDIS_CPUID_FLAG_KNC_MISC,
    ZYDIS_CPUID_FLAG_KNC_PF_HINT,
    ZYDIS_CPUID_FLAG_KOPB,
    ZYDIS_CPUID_FLAG_KOPD,
    ZYDIS_CPUID_FLAG_KOPQ,
    ZYDIS_CPUID_FLAG_KOPW,
    ZYDIS_CPUID_FLAG_LAHF,
    ZYDIS_CPUID_FLAG_LKGS,
    ZYDIS_CPUID_FLAG_LONGMODE,
    ZYDIS_CPUID_FLAG_LWP,
    ZYDIS_CPUID_FLAG_LZCNT,
    ZYDIS_CPUID_FLAG_MCOMMIT,
    ZYDIS_CPUID_FLAG_MONITOR,
    ZYDIS_CPUID_FLAG_MONITORX,
    ZYDIS_CPUID_FLAG_MOVBE,
    ZYDIS_CPUID_FLAG_MOVDIR,
    ZYDIS_CPUID_FLAG_MOVDIR64B,
    ZYDIS_CPUID_FLAG_MOVDIRI,
    ZYDIS_CPUID_FLAG_MPX,
    ZYDIS_CPUID_FLAG_MSRLIST,
    ZYDIS_CPUID_FLAG_PADLOCK_ACE,
    ZYDIS_CPUID_FLAG_PADLOCK_PHE,
    ZYDIS_CPUID_FLAG_PADLOCK_PMM,
    ZYDIS_CPUID_FLAG_PADLOCK_RNG,
    ZYDIS_CPUID_FLAG_PAUSE,
    ZYDIS_CPUID_FLAG_PBNDKB,
    ZYDIS_CPUID_FLAG_PCLMULQDQ,
    ZYDIS_CPUID_FLAG_PCOMMIT,
    ZYDIS_CPUID_FLAG_PCONFIG,
    ZYDIS_CPUID_FLAG_PENTIUMMMX,
    ZYDIS_CPUID_FLAG_PENTIUMREAL,
    ZYDIS_CPUID_FLAG_PKU,
    ZYDIS_CPUID_FLAG_POPCNT,
    ZYDIS_CPUID_FLAG_PPRO,
    ZYDIS_CPUID_FLAG_PREFETCHWT1,
    ZYDIS_CPUID_FLAG_PREFETCH_NOP,
    ZYDIS_CPUID_FLAG_PT,
    ZYDIS_CPUID_FLAG_RAO_INT,
    ZYDIS_CPUID_FLAG_RDPID,
    ZYDIS_CPUID_FLAG_RDPMC,
    ZYDIS_CPUID_FLAG_RDPRU,
    ZYDIS_CPUID_FLAG_RDRAND,
    ZYDIS_CPUID_FLAG_RDSEED,
    ZYDIS_CPUID_FLAG_RDTSCP,
    ZYDIS_CPUID_FLAG_RDWRFSGS,
    ZYDIS_CPUID_FLAG_RTM,
    ZYDIS_CPUID_FLAG_SERIALIZE,
    ZYDIS_CPUID_FLAG_SGX,
    ZYDIS_CPUID_FLAG_SGX_ENCLV,
    ZYDIS_CPUID_FLAG_SHA,
    ZYDIS_CPUID_FLAG_SHA512,
    ZYDIS_CPUID_FLAG_SM3,
    ZYDIS_CPUID_FLAG_SM4,
    ZYDIS_CPUID_FLAG_SMAP,
    ZYDIS_CPUID_FLAG_SMX,
    ZYDIS_CPUID_FLAG_SNP,
    ZYDIS_CPUID_FLAG_SSE,
    ZYDIS_CPUID_FLAG_SSE2,
    ZYDIS_CPUID_FLAG_SSE2MMX,
    ZYDIS_CPUID_FLAG_SSE3,
    ZYDIS_CPUID_FLAG_SSE3X87,
    ZYDIS_CPUID_FLAG_SSE4,
    ZYDIS_CPUID_FLAG_SSE42,
    ZYDIS_CPUID_FLAG_SSE4A,
    ZYDIS_CPUID_FLAG_SSEMXCSR,
    ZYDIS_CPUID_FLAG_SSE_PREFETCH,
    ZYDIS_CPUID_FLAG_SSSE3,
    ZYDIS_CPUID_FLAG_SSSE3MMX,
    ZYDIS_CPUID_FLAG_SVM,
    ZYDIS_CPUID_FLAG_TBM,
    ZYDIS_CPUID_FLAG_TDX,
    ZYDIS_CPUID_FLAG_TSX_LDTRK,
    ZYDIS_CPUID_FLAG_UINTR,
    ZYDIS_CPUID_FLAG_USER_MSR,
    ZYDIS_CPUID_FLAG_VAES,
    ZYDIS_CPUID_FLAG_VMFUNC,
    ZYDIS_CPUID_FLAG_VMX,
    ZYDIS_CPUID_FLAG_VPCLMULQDQ,
    ZYDIS_CPUID_FLAG_VTX,
    ZYDIS_CPUID_FLAG_WAITPKG,
    ZYDIS_CPUID_FLAG_WRMSRNS,
    ZYDIS_CPUID_FLAG_X87,
    ZYDIS_CPUID_FLAG_XOP,
    ZYDIS_CPUID_FLAG_XSAVE,
    ZYDIS_CPUID_FLAG_XSAVEC,
    ZYDIS_CPUID_FLAG_XSAVEOPT,
    ZYDIS_CPUID_FLAG_XSAVES,

    ZYDIS_CPUID_FLAG_MAX_VALUE = ZYDIS_CPUID_FLAG_XSAVES,
    ZYDIS_CPUID_FLAG_REQUIRED_BITS = ZYAN_BITS_TO_REPRESENT(ZYDIS_CPUID_FLAG_MAX_VALUE)
} ZydisCpuidFlag;

/**
 * Writes the CPUID feature flags for a decoded instruction into `flags`.
 *
 * `count` receives how many flags the instruction has. When `capacity` is
 * smaller than that, nothing is written and the status is
 * `ZYAN_STATUS_INSUFFICIENT_BUFFER_SIZE`.
 *
 * @param   instruction     Decoded instruction.
 * @param   flags           Caller buffer. May be null when `capacity` is 0.
 * @param   capacity        Number of `ZydisCpuidFlag` slots in `flags`.
 * @param   count           Receives the number of flags.
 *
 * @return  A zyan status code.
 */
ZYDIS_EXPORT ZyanStatus ZydisGetCpuidFlags(const ZydisDecodedInstruction* instruction,
    ZydisCpuidFlag* flags, ZyanU8 capacity, ZyanU8* count);

/**
 * Returns the name of a CPUID feature flag, or `ZYAN_NULL` when `flag` is out of range.
 */
ZYDIS_EXPORT const char* ZydisCpuidFlagGetString(ZydisCpuidFlag flag);

#ifdef __cplusplus
}
#endif

#endif /* ZYDIS_CPUID_FLAGS_H */
