/***************************************************************************************************

  Zyan Disassembler Library (Zydis)

  Original Author : Florian Bernd

 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.

***************************************************************************************************/

#include <Zycore/LibC.h>
#include <Zydis/CpuidFlags.h>

/* Indexed by ZydisISASet. Regenerate when that enum changes. */
static const ZydisCpuidFlag ZYDIS_CPUID_FLAG_TABLE[][ZYDIS_CPUID_FLAG_MAX_COUNT] =
{
    { ZYDIS_CPUID_FLAG_NONE, ZYDIS_CPUID_FLAG_NONE }, /* INVALID */
    { ZYDIS_CPUID_FLAG_ADOX_ADCX, ZYDIS_CPUID_FLAG_NONE }, /* ADOX_ADCX */
    { ZYDIS_CPUID_FLAG_AES, ZYDIS_CPUID_FLAG_NONE }, /* AES */
    { ZYDIS_CPUID_FLAG_AMD, ZYDIS_CPUID_FLAG_NONE }, /* AMD */
    { ZYDIS_CPUID_FLAG_AMD3DNOW, ZYDIS_CPUID_FLAG_NONE }, /* AMD3DNOW */
    { ZYDIS_CPUID_FLAG_AMD_INVLPGB, ZYDIS_CPUID_FLAG_NONE }, /* AMD_INVLPGB */
    { ZYDIS_CPUID_FLAG_AMX_BF16, ZYDIS_CPUID_FLAG_NONE }, /* AMX_BF16 */
    { ZYDIS_CPUID_FLAG_AMX_FP16, ZYDIS_CPUID_FLAG_NONE }, /* AMX_FP16 */
    { ZYDIS_CPUID_FLAG_AMX_INT8, ZYDIS_CPUID_FLAG_NONE }, /* AMX_INT8 */
    { ZYDIS_CPUID_FLAG_AMX_TILE, ZYDIS_CPUID_FLAG_NONE }, /* AMX_TILE */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_NONE }, /* APX_F */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_ADX }, /* APX_F_ADX */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_AMX }, /* APX_F_AMX */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_BMI1 }, /* APX_F_BMI1 */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_BMI2 }, /* APX_F_BMI2 */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_CET }, /* APX_F_CET */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_CMPCCXADD }, /* APX_F_CMPCCXADD */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_ENQCMD }, /* APX_F_ENQCMD */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_INVPCID }, /* APX_F_INVPCID */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_KOPB }, /* APX_F_KOPB */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_KOPD }, /* APX_F_KOPD */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_KOPQ }, /* APX_F_KOPQ */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_KOPW }, /* APX_F_KOPW */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_LZCNT }, /* APX_F_LZCNT */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_MOVBE }, /* APX_F_MOVBE */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_MOVDIR64B }, /* APX_F_MOVDIR64B */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_MOVDIRI }, /* APX_F_MOVDIRI */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_POPCNT }, /* APX_F_POPCNT */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_RAO_INT }, /* APX_F_RAO_INT */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_USER_MSR }, /* APX_F_USER_MSR */
    { ZYDIS_CPUID_FLAG_APX_F, ZYDIS_CPUID_FLAG_VMX }, /* APX_F_VMX */
    { ZYDIS_CPUID_FLAG_AVX, ZYDIS_CPUID_FLAG_NONE }, /* AVX */
    { ZYDIS_CPUID_FLAG_AVX2, ZYDIS_CPUID_FLAG_NONE }, /* AVX2 */
    { ZYDIS_CPUID_FLAG_AVX2GATHER, ZYDIS_CPUID_FLAG_NONE }, /* AVX2GATHER */
    { ZYDIS_CPUID_FLAG_AVX512BW, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512BW_128 */
    { ZYDIS_CPUID_FLAG_AVX512BW, ZYDIS_CPUID_FLAG_NONE }, /* AVX512BW_128N */
    { ZYDIS_CPUID_FLAG_AVX512BW, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512BW_256 */
    { ZYDIS_CPUID_FLAG_AVX512BW, ZYDIS_CPUID_FLAG_NONE }, /* AVX512BW_512 */
    { ZYDIS_CPUID_FLAG_AVX512BW, ZYDIS_CPUID_FLAG_NONE }, /* AVX512BW_KOP */
    { ZYDIS_CPUID_FLAG_AVX512CD, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512CD_128 */
    { ZYDIS_CPUID_FLAG_AVX512CD, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512CD_256 */
    { ZYDIS_CPUID_FLAG_AVX512CD, ZYDIS_CPUID_FLAG_NONE }, /* AVX512CD_512 */
    { ZYDIS_CPUID_FLAG_AVX512DQ, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512DQ_128 */
    { ZYDIS_CPUID_FLAG_AVX512DQ, ZYDIS_CPUID_FLAG_NONE }, /* AVX512DQ_128N */
    { ZYDIS_CPUID_FLAG_AVX512DQ, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512DQ_256 */
    { ZYDIS_CPUID_FLAG_AVX512DQ, ZYDIS_CPUID_FLAG_NONE }, /* AVX512DQ_512 */
    { ZYDIS_CPUID_FLAG_AVX512DQ, ZYDIS_CPUID_FLAG_NONE }, /* AVX512DQ_KOP */
    { ZYDIS_CPUID_FLAG_AVX512DQ, ZYDIS_CPUID_FLAG_NONE }, /* AVX512DQ_SCALAR */
    { ZYDIS_CPUID_FLAG_AVX512ER, ZYDIS_CPUID_FLAG_NONE }, /* AVX512ER_512 */
    { ZYDIS_CPUID_FLAG_AVX512ER, ZYDIS_CPUID_FLAG_NONE }, /* AVX512ER_SCALAR */
    { ZYDIS_CPUID_FLAG_AVX512F, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512F_128 */
    { ZYDIS_CPUID_FLAG_AVX512F, ZYDIS_CPUID_FLAG_NONE }, /* AVX512F_128N */
    { ZYDIS_CPUID_FLAG_AVX512F, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512F_256 */
    { ZYDIS_CPUID_FLAG_AVX512F, ZYDIS_CPUID_FLAG_NONE }, /* AVX512F_512 */
    { ZYDIS_CPUID_FLAG_AVX512F, ZYDIS_CPUID_FLAG_NONE }, /* AVX512F_KOP */
    { ZYDIS_CPUID_FLAG_AVX512F, ZYDIS_CPUID_FLAG_NONE }, /* AVX512F_SCALAR */
    { ZYDIS_CPUID_FLAG_AVX512PF, ZYDIS_CPUID_FLAG_NONE }, /* AVX512PF_512 */
    { ZYDIS_CPUID_FLAG_AVX512_4FMAPS, ZYDIS_CPUID_FLAG_NONE }, /* AVX512_4FMAPS_512 */
    { ZYDIS_CPUID_FLAG_AVX512_4FMAPS, ZYDIS_CPUID_FLAG_NONE }, /* AVX512_4FMAPS_SCALAR */
    { ZYDIS_CPUID_FLAG_AVX512_4VNNIW, ZYDIS_CPUID_FLAG_NONE }, /* AVX512_4VNNIW_512 */
    { ZYDIS_CPUID_FLAG_AVX512_BF16, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_BF16_128 */
    { ZYDIS_CPUID_FLAG_AVX512_BF16, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_BF16_256 */
    { ZYDIS_CPUID_FLAG_AVX512_BF16, ZYDIS_CPUID_FLAG_NONE }, /* AVX512_BF16_512 */
    { ZYDIS_CPUID_FLAG_AVX512_BITALG, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_BITALG_128 */
    { ZYDIS_CPUID_FLAG_AVX512_BITALG, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_BITALG_256 */
    { ZYDIS_CPUID_FLAG_AVX512_BITALG, ZYDIS_CPUID_FLAG_NONE }, /* AVX512_BITALG_512 */
    { ZYDIS_CPUID_FLAG_AVX512_FP16, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_FP16_128 */
    { ZYDIS_CPUID_FLAG_AVX512_FP16, ZYDIS_CPUID_FLAG_NONE }, /* AVX512_FP16_128N */
    { ZYDIS_CPUID_FLAG_AVX512_FP16, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_FP16_256 */
    { ZYDIS_CPUID_FLAG_AVX512_FP16, ZYDIS_CPUID_FLAG_NONE }, /* AVX512_FP16_512 */
    { ZYDIS_CPUID_FLAG_AVX512_FP16, ZYDIS_CPUID_FLAG_NONE }, /* AVX512_FP16_SCALAR */
    { ZYDIS_CPUID_FLAG_AVX512_GFNI, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_GFNI_128 */
    { ZYDIS_CPUID_FLAG_AVX512_GFNI, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_GFNI_256 */
    { ZYDIS_CPUID_FLAG_AVX512_GFNI, ZYDIS_CPUID_FLAG_NONE }, /* AVX512_GFNI_512 */
    { ZYDIS_CPUID_FLAG_AVX512_IFMA, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_IFMA_128 */
    { ZYDIS_CPUID_FLAG_AVX512_IFMA, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_IFMA_256 */
    { ZYDIS_CPUID_FLAG_AVX512_IFMA, ZYDIS_CPUID_FLAG_NONE }, /* AVX512_IFMA_512 */
    { ZYDIS_CPUID_FLAG_AVX512_VAES, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_VAES_128 */
    { ZYDIS_CPUID_FLAG_AVX512_VAES, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_VAES_256 */
    { ZYDIS_CPUID_FLAG_AVX512_VAES, ZYDIS_CPUID_FLAG_NONE }, /* AVX512_VAES_512 */
    { ZYDIS_CPUID_FLAG_AVX512_VBMI2, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_VBMI2_128 */
    { ZYDIS_CPUID_FLAG_AVX512_VBMI2, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_VBMI2_256 */
    { ZYDIS_CPUID_FLAG_AVX512_VBMI2, ZYDIS_CPUID_FLAG_NONE }, /* AVX512_VBMI2_512 */
    { ZYDIS_CPUID_FLAG_AVX512_VBMI, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_VBMI_128 */
    { ZYDIS_CPUID_FLAG_AVX512_VBMI, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_VBMI_256 */
    { ZYDIS_CPUID_FLAG_AVX512_VBMI, ZYDIS_CPUID_FLAG_NONE }, /* AVX512_VBMI_512 */
    { ZYDIS_CPUID_FLAG_AVX512_VNNI, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_VNNI_128 */
    { ZYDIS_CPUID_FLAG_AVX512_VNNI, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_VNNI_256 */
    { ZYDIS_CPUID_FLAG_AVX512_VNNI, ZYDIS_CPUID_FLAG_NONE }, /* AVX512_VNNI_512 */
    { ZYDIS_CPUID_FLAG_AVX512_VP2INTERSECT, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_VP2INTERSECT_128 */
    { ZYDIS_CPUID_FLAG_AVX512_VP2INTERSECT, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_VP2INTERSECT_256 */
    { ZYDIS_CPUID_FLAG_AVX512_VP2INTERSECT, ZYDIS_CPUID_FLAG_NONE }, /* AVX512_VP2INTERSECT_512 */
    { ZYDIS_CPUID_FLAG_AVX512_VPCLMULQDQ, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_VPCLMULQDQ_128 */
    { ZYDIS_CPUID_FLAG_AVX512_VPCLMULQDQ, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_VPCLMULQDQ_256 */
    { ZYDIS_CPUID_FLAG_AVX512_VPCLMULQDQ, ZYDIS_CPUID_FLAG_NONE }, /* AVX512_VPCLMULQDQ_512 */
    { ZYDIS_CPUID_FLAG_AVX512_VPOPCNTDQ, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_VPOPCNTDQ_128 */
    { ZYDIS_CPUID_FLAG_AVX512_VPOPCNTDQ, ZYDIS_CPUID_FLAG_AVX512VL }, /* AVX512_VPOPCNTDQ_256 */
    { ZYDIS_CPUID_FLAG_AVX512_VPOPCNTDQ, ZYDIS_CPUID_FLAG_NONE }, /* AVX512_VPOPCNTDQ_512 */
    { ZYDIS_CPUID_FLAG_AVXAES, ZYDIS_CPUID_FLAG_NONE }, /* AVXAES */
    { ZYDIS_CPUID_FLAG_AVX_GFNI, ZYDIS_CPUID_FLAG_NONE }, /* AVX_GFNI */
    { ZYDIS_CPUID_FLAG_AVX_IFMA, ZYDIS_CPUID_FLAG_NONE }, /* AVX_IFMA */
    { ZYDIS_CPUID_FLAG_AVX_NE_CONVERT, ZYDIS_CPUID_FLAG_NONE }, /* AVX_NE_CONVERT */
    { ZYDIS_CPUID_FLAG_AVX_VNNI, ZYDIS_CPUID_FLAG_NONE }, /* AVX_VNNI */
    { ZYDIS_CPUID_FLAG_AVX_VNNI_INT16, ZYDIS_CPUID_FLAG_NONE }, /* AVX_VNNI_INT16 */
    { ZYDIS_CPUID_FLAG_AVX_VNNI_INT8, ZYDIS_CPUID_FLAG_NONE }, /* AVX_VNNI_INT8 */
    { ZYDIS_CPUID_FLAG_BMI1, ZYDIS_CPUID_FLAG_NONE }, /* BMI1 */
    { ZYDIS_CPUID_FLAG_BMI2, ZYDIS_CPUID_FLAG_NONE }, /* BMI2 */
    { ZYDIS_CPUID_FLAG_CET, ZYDIS_CPUID_FLAG_NONE }, /* CET */
    { ZYDIS_CPUID_FLAG_CLDEMOTE, ZYDIS_CPUID_FLAG_NONE }, /* CLDEMOTE */
    { ZYDIS_CPUID_FLAG_CLFLUSHOPT, ZYDIS_CPUID_FLAG_NONE }, /* CLFLUSHOPT */
    { ZYDIS_CPUID_FLAG_CLFSH, ZYDIS_CPUID_FLAG_NONE }, /* CLFSH */
    { ZYDIS_CPUID_FLAG_CLWB, ZYDIS_CPUID_FLAG_NONE }, /* CLWB */
    { ZYDIS_CPUID_FLAG_CLZERO, ZYDIS_CPUID_FLAG_NONE }, /* CLZERO */
    { ZYDIS_CPUID_FLAG_CMOV, ZYDIS_CPUID_FLAG_NONE }, /* CMOV */
    { ZYDIS_CPUID_FLAG_CMPXCHG16B, ZYDIS_CPUID_FLAG_NONE }, /* CMPXCHG16B */
    { ZYDIS_CPUID_FLAG_ENQCMD, ZYDIS_CPUID_FLAG_NONE }, /* ENQCMD */
    { ZYDIS_CPUID_FLAG_F16C, ZYDIS_CPUID_FLAG_NONE }, /* F16C */
    { ZYDIS_CPUID_FLAG_FAT_NOP, ZYDIS_CPUID_FLAG_NONE }, /* FAT_NOP */
    { ZYDIS_CPUID_FLAG_FCMOV, ZYDIS_CPUID_FLAG_NONE }, /* FCMOV */
    { ZYDIS_CPUID_FLAG_FCOMI, ZYDIS_CPUID_FLAG_NONE }, /* FCOMI */
    { ZYDIS_CPUID_FLAG_FMA, ZYDIS_CPUID_FLAG_NONE }, /* FMA */
    { ZYDIS_CPUID_FLAG_FMA4, ZYDIS_CPUID_FLAG_NONE }, /* FMA4 */
    { ZYDIS_CPUID_FLAG_FRED, ZYDIS_CPUID_FLAG_NONE }, /* FRED */
    { ZYDIS_CPUID_FLAG_FXSAVE, ZYDIS_CPUID_FLAG_NONE }, /* FXSAVE */
    { ZYDIS_CPUID_FLAG_FXSAVE64, ZYDIS_CPUID_FLAG_NONE }, /* FXSAVE64 */
    { ZYDIS_CPUID_FLAG_GFNI, ZYDIS_CPUID_FLAG_NONE }, /* GFNI */
    { ZYDIS_CPUID_FLAG_HRESET, ZYDIS_CPUID_FLAG_NONE }, /* HRESET */
    { ZYDIS_CPUID_FLAG_I186, ZYDIS_CPUID_FLAG_NONE }, /* I186 */
    { ZYDIS_CPUID_FLAG_I286PROTECTED, ZYDIS_CPUID_FLAG_NONE }, /* I286PROTECTED */
    { ZYDIS_CPUID_FLAG_I286REAL, ZYDIS_CPUID_FLAG_NONE }, /* I286REAL */
    { ZYDIS_CPUID_FLAG_I386, ZYDIS_CPUID_FLAG_NONE }, /* I386 */
    { ZYDIS_CPUID_FLAG_I486, ZYDIS_CPUID_FLAG_NONE }, /* I486 */
    { ZYDIS_CPUID_FLAG_I486REAL, ZYDIS_CPUID_FLAG_NONE }, /* I486REAL */
    { ZYDIS_CPUID_FLAG_I86, ZYDIS_CPUID_FLAG_NONE }, /* I86 */
    { ZYDIS_CPUID_FLAG_ICACHE_PREFETCH, ZYDIS_CPUID_FLAG_NONE }, /* ICACHE_PREFETCH */
    { ZYDIS_CPUID_FLAG_INVPCID, ZYDIS_CPUID_FLAG_NONE }, /* INVPCID */
    { ZYDIS_CPUID_FLAG_KEYLOCKER, ZYDIS_CPUID_FLAG_NONE }, /* KEYLOCKER */
    { ZYDIS_CPUID_FLAG_KEYLOCKER_WIDE, ZYDIS_CPUID_FLAG_NONE }, /* KEYLOCKER_WIDE */
    { ZYDIS_CPUID_FLAG_KNCE, ZYDIS_CPUID_FLAG_NONE }, /* KNCE */
    { ZYDIS_CPUID_FLAG_KNCJKBR, ZYDIS_CPUID_FLAG_NONE }, /* KNCJKBR */
    { ZYDIS_CPUID_FLAG_KNCSTREAM, ZYDIS_CPUID_FLAG_NONE }, /* KNCSTREAM */
    { ZYDIS_CPUID_FLAG_KNCV, ZYDIS_CPUID_FLAG_NONE }, /* KNCV */
    { ZYDIS_CPUID_FLAG_KNC_MISC, ZYDIS_CPUID_FLAG_NONE }, /* KNC_MISC */
    { ZYDIS_CPUID_FLAG_KNC_PF_HINT, ZYDIS_CPUID_FLAG_NONE }, /* KNC_PF_HINT */
    { ZYDIS_CPUID_FLAG_LAHF, ZYDIS_CPUID_FLAG_NONE }, /* LAHF */
    { ZYDIS_CPUID_FLAG_LKGS, ZYDIS_CPUID_FLAG_NONE }, /* LKGS */
    { ZYDIS_CPUID_FLAG_LONGMODE, ZYDIS_CPUID_FLAG_NONE }, /* LONGMODE */
    { ZYDIS_CPUID_FLAG_LWP, ZYDIS_CPUID_FLAG_NONE }, /* LWP */
    { ZYDIS_CPUID_FLAG_LZCNT, ZYDIS_CPUID_FLAG_NONE }, /* LZCNT */
    { ZYDIS_CPUID_FLAG_MCOMMIT, ZYDIS_CPUID_FLAG_NONE }, /* MCOMMIT */
    { ZYDIS_CPUID_FLAG_MONITOR, ZYDIS_CPUID_FLAG_NONE }, /* MONITOR */
    { ZYDIS_CPUID_FLAG_MONITORX, ZYDIS_CPUID_FLAG_NONE }, /* MONITORX */
    { ZYDIS_CPUID_FLAG_MOVBE, ZYDIS_CPUID_FLAG_NONE }, /* MOVBE */
    { ZYDIS_CPUID_FLAG_MOVDIR, ZYDIS_CPUID_FLAG_NONE }, /* MOVDIR */
    { ZYDIS_CPUID_FLAG_MPX, ZYDIS_CPUID_FLAG_NONE }, /* MPX */
    { ZYDIS_CPUID_FLAG_MSRLIST, ZYDIS_CPUID_FLAG_NONE }, /* MSRLIST */
    { ZYDIS_CPUID_FLAG_PADLOCK_ACE, ZYDIS_CPUID_FLAG_NONE }, /* PADLOCK_ACE */
    { ZYDIS_CPUID_FLAG_PADLOCK_PHE, ZYDIS_CPUID_FLAG_NONE }, /* PADLOCK_PHE */
    { ZYDIS_CPUID_FLAG_PADLOCK_PMM, ZYDIS_CPUID_FLAG_NONE }, /* PADLOCK_PMM */
    { ZYDIS_CPUID_FLAG_PADLOCK_RNG, ZYDIS_CPUID_FLAG_NONE }, /* PADLOCK_RNG */
    { ZYDIS_CPUID_FLAG_PAUSE, ZYDIS_CPUID_FLAG_NONE }, /* PAUSE */
    { ZYDIS_CPUID_FLAG_PBNDKB, ZYDIS_CPUID_FLAG_NONE }, /* PBNDKB */
    { ZYDIS_CPUID_FLAG_PCLMULQDQ, ZYDIS_CPUID_FLAG_NONE }, /* PCLMULQDQ */
    { ZYDIS_CPUID_FLAG_PCOMMIT, ZYDIS_CPUID_FLAG_NONE }, /* PCOMMIT */
    { ZYDIS_CPUID_FLAG_PCONFIG, ZYDIS_CPUID_FLAG_NONE }, /* PCONFIG */
    { ZYDIS_CPUID_FLAG_PENTIUMMMX, ZYDIS_CPUID_FLAG_NONE }, /* PENTIUMMMX */
    { ZYDIS_CPUID_FLAG_PENTIUMREAL, ZYDIS_CPUID_FLAG_NONE }, /* PENTIUMREAL */
    { ZYDIS_CPUID_FLAG_PKU, ZYDIS_CPUID_FLAG_NONE }, /* PKU */
    { ZYDIS_CPUID_FLAG_POPCNT, ZYDIS_CPUID_FLAG_NONE }, /* POPCNT */
    { ZYDIS_CPUID_FLAG_PPRO, ZYDIS_CPUID_FLAG_NONE }, /* PPRO */
    { ZYDIS_CPUID_FLAG_PREFETCHWT1, ZYDIS_CPUID_FLAG_NONE }, /* PREFETCHWT1 */
    { ZYDIS_CPUID_FLAG_PREFETCH_NOP, ZYDIS_CPUID_FLAG_NONE }, /* PREFETCH_NOP */
    { ZYDIS_CPUID_FLAG_PT, ZYDIS_CPUID_FLAG_NONE }, /* PT */
    { ZYDIS_CPUID_FLAG_RAO_INT, ZYDIS_CPUID_FLAG_NONE }, /* RAO_INT */
    { ZYDIS_CPUID_FLAG_RDPID, ZYDIS_CPUID_FLAG_NONE }, /* RDPID */
    { ZYDIS_CPUID_FLAG_RDPMC, ZYDIS_CPUID_FLAG_NONE }, /* RDPMC */
    { ZYDIS_CPUID_FLAG_RDPRU, ZYDIS_CPUID_FLAG_NONE }, /* RDPRU */
    { ZYDIS_CPUID_FLAG_RDRAND, ZYDIS_CPUID_FLAG_NONE }, /* RDRAND */
    { ZYDIS_CPUID_FLAG_RDSEED, ZYDIS_CPUID_FLAG_NONE }, /* RDSEED */
    { ZYDIS_CPUID_FLAG_RDTSCP, ZYDIS_CPUID_FLAG_NONE }, /* RDTSCP */
    { ZYDIS_CPUID_FLAG_RDWRFSGS, ZYDIS_CPUID_FLAG_NONE }, /* RDWRFSGS */
    { ZYDIS_CPUID_FLAG_RTM, ZYDIS_CPUID_FLAG_NONE }, /* RTM */
    { ZYDIS_CPUID_FLAG_SERIALIZE, ZYDIS_CPUID_FLAG_NONE }, /* SERIALIZE */
    { ZYDIS_CPUID_FLAG_SGX, ZYDIS_CPUID_FLAG_NONE }, /* SGX */
    { ZYDIS_CPUID_FLAG_SGX_ENCLV, ZYDIS_CPUID_FLAG_NONE }, /* SGX_ENCLV */
    { ZYDIS_CPUID_FLAG_SHA, ZYDIS_CPUID_FLAG_NONE }, /* SHA */
    { ZYDIS_CPUID_FLAG_SHA512, ZYDIS_CPUID_FLAG_NONE }, /* SHA512 */
    { ZYDIS_CPUID_FLAG_SM3, ZYDIS_CPUID_FLAG_NONE }, /* SM3 */
    { ZYDIS_CPUID_FLAG_SM4, ZYDIS_CPUID_FLAG_NONE }, /* SM4 */
    { ZYDIS_CPUID_FLAG_SMAP, ZYDIS_CPUID_FLAG_NONE }, /* SMAP */
    { ZYDIS_CPUID_FLAG_SMX, ZYDIS_CPUID_FLAG_NONE }, /* SMX */
    { ZYDIS_CPUID_FLAG_SNP, ZYDIS_CPUID_FLAG_NONE }, /* SNP */
    { ZYDIS_CPUID_FLAG_SSE, ZYDIS_CPUID_FLAG_NONE }, /* SSE */
    { ZYDIS_CPUID_FLAG_SSE2, ZYDIS_CPUID_FLAG_NONE }, /* SSE2 */
    { ZYDIS_CPUID_FLAG_SSE2MMX, ZYDIS_CPUID_FLAG_NONE }, /* SSE2MMX */
    { ZYDIS_CPUID_FLAG_SSE3, ZYDIS_CPUID_FLAG_NONE }, /* SSE3 */
    { ZYDIS_CPUID_FLAG_SSE3X87, ZYDIS_CPUID_FLAG_NONE }, /* SSE3X87 */
    { ZYDIS_CPUID_FLAG_SSE4, ZYDIS_CPUID_FLAG_NONE }, /* SSE4 */
    { ZYDIS_CPUID_FLAG_SSE42, ZYDIS_CPUID_FLAG_NONE }, /* SSE42 */
    { ZYDIS_CPUID_FLAG_SSE4A, ZYDIS_CPUID_FLAG_NONE }, /* SSE4A */
    { ZYDIS_CPUID_FLAG_SSEMXCSR, ZYDIS_CPUID_FLAG_NONE }, /* SSEMXCSR */
    { ZYDIS_CPUID_FLAG_SSE_PREFETCH, ZYDIS_CPUID_FLAG_NONE }, /* SSE_PREFETCH */
    { ZYDIS_CPUID_FLAG_SSSE3, ZYDIS_CPUID_FLAG_NONE }, /* SSSE3 */
    { ZYDIS_CPUID_FLAG_SSSE3MMX, ZYDIS_CPUID_FLAG_NONE }, /* SSSE3MMX */
    { ZYDIS_CPUID_FLAG_SVM, ZYDIS_CPUID_FLAG_NONE }, /* SVM */
    { ZYDIS_CPUID_FLAG_TBM, ZYDIS_CPUID_FLAG_NONE }, /* TBM */
    { ZYDIS_CPUID_FLAG_TDX, ZYDIS_CPUID_FLAG_NONE }, /* TDX */
    { ZYDIS_CPUID_FLAG_TSX_LDTRK, ZYDIS_CPUID_FLAG_NONE }, /* TSX_LDTRK */
    { ZYDIS_CPUID_FLAG_UINTR, ZYDIS_CPUID_FLAG_NONE }, /* UINTR */
    { ZYDIS_CPUID_FLAG_VAES, ZYDIS_CPUID_FLAG_NONE }, /* VAES */
    { ZYDIS_CPUID_FLAG_VMFUNC, ZYDIS_CPUID_FLAG_NONE }, /* VMFUNC */
    { ZYDIS_CPUID_FLAG_VPCLMULQDQ, ZYDIS_CPUID_FLAG_NONE }, /* VPCLMULQDQ */
    { ZYDIS_CPUID_FLAG_VTX, ZYDIS_CPUID_FLAG_NONE }, /* VTX */
    { ZYDIS_CPUID_FLAG_WAITPKG, ZYDIS_CPUID_FLAG_NONE }, /* WAITPKG */
    { ZYDIS_CPUID_FLAG_WRMSRNS, ZYDIS_CPUID_FLAG_NONE }, /* WRMSRNS */
    { ZYDIS_CPUID_FLAG_X87, ZYDIS_CPUID_FLAG_NONE }, /* X87 */
    { ZYDIS_CPUID_FLAG_XOP, ZYDIS_CPUID_FLAG_NONE }, /* XOP */
    { ZYDIS_CPUID_FLAG_XSAVE, ZYDIS_CPUID_FLAG_NONE }, /* XSAVE */
    { ZYDIS_CPUID_FLAG_XSAVEC, ZYDIS_CPUID_FLAG_NONE }, /* XSAVEC */
    { ZYDIS_CPUID_FLAG_XSAVEOPT, ZYDIS_CPUID_FLAG_NONE }, /* XSAVEOPT */
    { ZYDIS_CPUID_FLAG_XSAVES, ZYDIS_CPUID_FLAG_NONE }, /* XSAVES */
};

ZYAN_STATIC_ASSERT((sizeof(ZYDIS_CPUID_FLAG_TABLE) / sizeof(ZYDIS_CPUID_FLAG_TABLE[0])) ==
    (ZYDIS_ISA_SET_MAX_VALUE + 1));

ZyanStatus ZydisGetCpuidFlags(const ZydisDecodedInstruction* instruction,
    ZydisCpuidFlag* flags, ZyanU8 capacity, ZyanU8* count)
{
    const ZydisCpuidFlag* row;
    ZyanU8 n = 0;
    ZyanU8 i;

    if (!instruction || !count || (capacity && !flags) ||
        (instruction->meta.isa_set > ZYDIS_ISA_SET_MAX_VALUE))
    {
        return ZYAN_STATUS_INVALID_ARGUMENT;
    }

    row = ZYDIS_CPUID_FLAG_TABLE[instruction->meta.isa_set];
    for (i = 0; i < ZYDIS_CPUID_FLAG_MAX_COUNT; ++i)
    {
        if (row[i] != ZYDIS_CPUID_FLAG_NONE)
        {
            ++n;
        }
    }
    *count = n;
    if (capacity < n)
    {
        return ZYAN_STATUS_INSUFFICIENT_BUFFER_SIZE;
    }
    /* A plain loop becomes memmove at -O2, which the nostdlib build does not provide. */
    if (n)
    {
        ZYAN_MEMCPY(flags, row, (ZyanUSize)n * sizeof(*flags));
    }
    return ZYAN_STATUS_SUCCESS;
}

static const char* const ZYDIS_CPUID_FLAG_NAMES[] =
{
    "NONE",
    "ADOX_ADCX",
    "ADX",
    "AES",
    "AMD",
    "AMD3DNOW",
    "AMD_INVLPGB",
    "AMX",
    "AMX_BF16",
    "AMX_FP16",
    "AMX_INT8",
    "AMX_TILE",
    "APX_F",
    "AVX",
    "AVX2",
    "AVX2GATHER",
    "AVX512BW",
    "AVX512CD",
    "AVX512DQ",
    "AVX512ER",
    "AVX512F",
    "AVX512PF",
    "AVX512VL",
    "AVX512_4FMAPS",
    "AVX512_4VNNIW",
    "AVX512_BF16",
    "AVX512_BITALG",
    "AVX512_FP16",
    "AVX512_GFNI",
    "AVX512_IFMA",
    "AVX512_VAES",
    "AVX512_VBMI",
    "AVX512_VBMI2",
    "AVX512_VNNI",
    "AVX512_VP2INTERSECT",
    "AVX512_VPCLMULQDQ",
    "AVX512_VPOPCNTDQ",
    "AVXAES",
    "AVX_GFNI",
    "AVX_IFMA",
    "AVX_NE_CONVERT",
    "AVX_VNNI",
    "AVX_VNNI_INT16",
    "AVX_VNNI_INT8",
    "BMI1",
    "BMI2",
    "CET",
    "CLDEMOTE",
    "CLFLUSHOPT",
    "CLFSH",
    "CLWB",
    "CLZERO",
    "CMOV",
    "CMPCCXADD",
    "CMPXCHG16B",
    "ENQCMD",
    "F16C",
    "FAT_NOP",
    "FCMOV",
    "FCOMI",
    "FMA",
    "FMA4",
    "FRED",
    "FXSAVE",
    "FXSAVE64",
    "GFNI",
    "HRESET",
    "I186",
    "I286PROTECTED",
    "I286REAL",
    "I386",
    "I486",
    "I486REAL",
    "I86",
    "ICACHE_PREFETCH",
    "INVPCID",
    "KEYLOCKER",
    "KEYLOCKER_WIDE",
    "KNCE",
    "KNCJKBR",
    "KNCSTREAM",
    "KNCV",
    "KNC_MISC",
    "KNC_PF_HINT",
    "KOPB",
    "KOPD",
    "KOPQ",
    "KOPW",
    "LAHF",
    "LKGS",
    "LONGMODE",
    "LWP",
    "LZCNT",
    "MCOMMIT",
    "MONITOR",
    "MONITORX",
    "MOVBE",
    "MOVDIR",
    "MOVDIR64B",
    "MOVDIRI",
    "MPX",
    "MSRLIST",
    "PADLOCK_ACE",
    "PADLOCK_PHE",
    "PADLOCK_PMM",
    "PADLOCK_RNG",
    "PAUSE",
    "PBNDKB",
    "PCLMULQDQ",
    "PCOMMIT",
    "PCONFIG",
    "PENTIUMMMX",
    "PENTIUMREAL",
    "PKU",
    "POPCNT",
    "PPRO",
    "PREFETCHWT1",
    "PREFETCH_NOP",
    "PT",
    "RAO_INT",
    "RDPID",
    "RDPMC",
    "RDPRU",
    "RDRAND",
    "RDSEED",
    "RDTSCP",
    "RDWRFSGS",
    "RTM",
    "SERIALIZE",
    "SGX",
    "SGX_ENCLV",
    "SHA",
    "SHA512",
    "SM3",
    "SM4",
    "SMAP",
    "SMX",
    "SNP",
    "SSE",
    "SSE2",
    "SSE2MMX",
    "SSE3",
    "SSE3X87",
    "SSE4",
    "SSE42",
    "SSE4A",
    "SSEMXCSR",
    "SSE_PREFETCH",
    "SSSE3",
    "SSSE3MMX",
    "SVM",
    "TBM",
    "TDX",
    "TSX_LDTRK",
    "UINTR",
    "USER_MSR",
    "VAES",
    "VMFUNC",
    "VMX",
    "VPCLMULQDQ",
    "VTX",
    "WAITPKG",
    "WRMSRNS",
    "X87",
    "XOP",
    "XSAVE",
    "XSAVEC",
    "XSAVEOPT",
    "XSAVES",
};

ZYAN_STATIC_ASSERT((sizeof(ZYDIS_CPUID_FLAG_NAMES) / sizeof(ZYDIS_CPUID_FLAG_NAMES[0])) ==
    (ZYDIS_CPUID_FLAG_MAX_VALUE + 1));

const char* ZydisCpuidFlagGetString(ZydisCpuidFlag flag)
{
    if ((ZyanUSize)flag > ZYDIS_CPUID_FLAG_MAX_VALUE)
    {
        return ZYAN_NULL;
    }
    return ZYDIS_CPUID_FLAG_NAMES[flag];
}
